import React from 'react';
import type {Metadata} from 'next'
import UserProvider from '@/components/UserProvider';
import './globals.css'
import Image from 'next/image';
import Logo from './logo_full-nobg_196.png';
import {SidebarButton} from '@/components/SidebarButton';
import {Source_Sans_3} from "@next/font/google";

const sourceSans = Source_Sans_3({
    subsets: ["latin"],
    variable: "--font-source-sans"
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {

    return (
        <html lang="en" className={sourceSans.className}>
        <UserProvider>
            <body className="bg-stone-900 min-w-full h-screen">
            <div className="bg-stone-800 h-full fixed flex flex-col w-48 p-4 justify-start items-center">
                <Image src={Logo} width={128} alt='logo' className='mt-2 mb-4'/>
                <nav className="flex flex-col h-full w-full">
                    <SidebarButton label='Inicio' href='/' iconName='home' className='w-full'/>
                    <SidebarButton label='Grupos' href='/groups' iconName='groups' className='w-full'/>
                    <SidebarButton label='Alumnos' href='/students' iconName='school' className='w-full'/>
                    <SidebarButton label='Estadisticas' href='/statistics' iconName='bar_chart' className='w-full'/>
                    <SidebarButton label='Notificaciones' href='/notifications' iconName='notifications' className='w-full'/>
                    <SidebarButton label='Mi cuenta' href='/account' iconName='account_circle' className='w-full'/>
                    <div className="grow"/>
                    <SidebarButton label='Administración' href='/admin' iconName='admin_panel_settings' className='w-full'/>
                </nav>

            </div>
            <div className="max-w-[calc(100%-192px)] ml-48">
                {children}
            </div>
            </body>
        </UserProvider>
        </html>
    )
}
